FROM nginx:1.27-alpine

WORKDIR /var/www/html

COPY html_public /var/www/html/html_public
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /var/www/html/storage/app/public /var/www/html/html_public/modules \
    && rm -f /var/www/html/html_public/storage \
    && ln -s /var/www/html/storage/app/public /var/www/html/html_public/storage
